name: Deploy NodeJs APP
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          MAC_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: MAC_PASSWORD
          script: |
            export PATH=$PATH:/usr/local/bin:/opt/homebrew/bin:/Applications/Docker.app/Contents/Resources/bin

            # 1. Explicitly unlock the macOS keychain for this headless SSH session
            security unlock-keychain -p "$MAC_PASSWORD" ~/Library/Keychains/login.keychain-db

            # 2. Proceed with the deployment
            cd ~/Desktop/Deployment/mac_os_as_server
            git pull origin main 

            docker compose down 
            docker compose up -d --build
